sudo: required
dist: bionic
language: python # To use conan
python: "3.7"
compiler:
  - gcc

cache:
  directories:
  - $HOME/.conan

git:
  submodules: false

addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
    - libasound2-dev
    - luarocks
    - cmake
    - build-essential
    - autopoint
    - libjack-dev
    - libgtk2.0-dev
    - mesa-common-dev
    - libgl1-mesa-dev
    - libpulse-dev
    - libva-dev
    - libvdpau-dev
    - libxcb1-dev
    - libxcb-shm0-dev
    - libxcb-shape0-dev
    - libxcb-xfixes0-dev

matrix:
  include:
  - {}

install:
- sudo luarocks install busted > /dev/null
- sudo luarocks install moonscript > /dev/null
- sudo luarocks install uuid > /dev/null
# Remove the CMake provided by travis
- sudo rm -rf /usr/local/cmake*
- pip install conan
- conan user
- git clone https://github.com/cqjjjzr/Aegisub-Conan-CMake.git

script:
- cd tests
- ./setup.sh || travis_terminate 1;
- cd ..
- mkdir build-dir
- cd build-dir
# Force upload cache.
- timeout 1800 cmake -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wno-unused-parameter -pedantic' -DCMAKE_BUILD_TYPE='Release' -DCMAKE_C_FLAGS='-Wall' -DWITH_STARTUPLOG=ON -DWITH_CSRI=OFF -DWITH_TEST=ON -DDEPENDENCIES_CMAKE_FILE="./Aegisub-Conan-CMake/dependencies_conan.cmake" .. || travis_terminate 1;
- make -j2 || travis_terminate 1;
- make test-aegisub -j2 || travis_terminate 1;
- ctest --output-on-failure . || travis_terminate 1;

notifications:
  email:
  - on_success: change
  - on_failure: change

