name: CI

on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # (x64 or x86)
    - name: Initialize required apt packages
      run: |
        which cmake
        sudo rm -rf /usr/local/cmake*
        sudo apt-get remove cmake
        sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo add-apt-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
        sudo apt-get update
        sudo apt-get install libasound2-dev luarocks cmake autopoint libjack-dev libgtk2.0-dev mesa-common-dev libgl1-mesa-dev libpulse-dev libva-dev libvdpau-dev libxcb1-dev libxcb-shm0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name : Install Conan
      run: pip install conan
    - name : Install required luarock packages
      run: |
        sudo luarocks install busted > /dev/null
        sudo luarocks install moonscript > /dev/null
        sudo luarocks install uuid > /dev/null
    - name : Clone CMake dependencies resolving script
      uses : actions/checkout@v2
      with : 
        repository: cqjjjzr/Aegisub-Conan-CMake
        path: Aegisub-Conan-CMake
    - name: Cache
      id: cache-aegisub
      uses: actions/cache@v1
      with:
        path: ~/.conan
        key: ${{ runner.os }}-conan
    - name: Resolving dependencies and configuring CMake
      run: |
        conan user
        cd tests
        ./setup.sh
        cd ..
        mkdir build-dir
        cd build-dir
        cmake -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wno-unused-parameter -pedantic' -DCMAKE_BUILD_TYPE='Release' -DCMAKE_C_FLAGS='-Wall' -DWITH_STARTUPLOG=ON -DWITH_CSRI=OFF -DWITH_TEST=ON -DDEPENDENCIES_CMAKE_FILE="./Aegisub-Conan-CMake/dependencies_conan.cmake" ..
    - name : Build
      working-directory : build-dir
      run: |
        make -j2
        make test-aegisub -j2
    - name : Test
      working-directory : build-dir
      run: |
        ctest --output-on-failure .
